/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("com.rdebokx.ltga.App") //TODO: update this: run parallel by default (demo run)
}

/**
 * Executables
 */
task("RunSequential", JavaExec::class) {
    main = "com.rdebokx.ltga.sequential.executables.Main"
    args = listOf("ONEMAX", "10", "10", "100", "false", "0", "0.5", "25") //TODO: request this as input
    classpath = sourceSets["main"].runtimeClasspath
}

/**
 * Experiments
 */

//TODO
