package com.rdebokx.ltga.shared;

public enum Problem {
    ONEMAX, 
    DECEPTIVE_TRAP_4_TIGHT_ENCODING, 
    DECEPTIVE_TRAP_4_LOOSE_ENCODING, 
    DECEPTIVE_TRAP_5_TIGHT_ENCODING,
    DECEPTIVE_TRAP_5_LOOSE_ENCODING,
    NK_LANDSCAPES,
    MAXCUT,
    OPTIMAL_FIXED_FOS
}
